version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
      
  flower:
    image: mher/flower
    command: celery -A app.tasks.celery flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - rabbitmq
